log_dir: "Checkpoint"
save_freq: 10
device: "cuda"
epochs: 200
batch_size: 256
pretrained_model: ""
train_data: "Data/ko/train_list_phoneme_final.txt"
val_data: "Data/ko/val_list_phoneme_final.txt"

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 179 # _letters_ipa_ko 포함
  #  n_token: 80
   token_embedding_dim: 256

optimizer_params:
  lr: 0.0005

data_params:
  root_path: "/workspace/ai/raw/speech/TTS/News_Script_and_Anchor_Speech/Data"



